"""Generate the appendix's matched z_start=30/3400 growth tracks as vector TeX.

Run from the repository root: .venv/bin/python -m scripts.plot_early_start
"""
from pathlib import Path
import numpy as np
from src import models


def render():
    redshift = np.linspace(12, 6, 121)
    panels = []
    for index, epsilon in enumerate((0.1, 1 - np.sqrt(8 / 9))):
        tracks = {start: models.predicted_log_mbh(2, 1, epsilon, start, redshift)
                  for start in (30, 3400)}
        shift = float(tracks[3400][0] - tracks[30][0])
        low = float(models.predicted_log_mbh(2, 1, epsilon, 30, 8))
        # The offset must be independent of observed redshift for these histories.
        expected = models.growth_log10_factor(
            1, epsilon, models.cosmic_time_gyr(30) - models.cosmic_time_gyr(3400))
        np.testing.assert_allclose(tracks[3400] - tracks[30], expected, atol=1e-12)
        plots = []
        for start, style in ((30, 'atlasblue,solid'), (3400, 'earlyorange,dashed')):
            coordinates = ' '.join(f'({z:.5f},{mass:.8f})'
                                   for z, mass in zip(redshift, tracks[start]))
            plots.append(r'\addplot[' + style + ',line width=1.2pt] coordinates {'
                         + coordinates + '};')
        title = rf'({chr(97 + index)}) $\epsilon={epsilon:.5f}$'
        panels.append(r'''\begin{minipage}[t]{0.485\textwidth}
\centering
\begin{tikzpicture}
\begin{axis}[
width=\linewidth,height=5.8cm,
xmin=6,xmax=12,x dir=reverse,xtick={6,7,8,9,10,11,12},
xlabel={Observed redshift},ylabel={$\log_{10}(M_{\rm BH}/M_\odot)$},
title={TITLE},title style={at={(0,1.04)},anchor=south west},
tick label style={font=\small},label style={font=\small},
axis lines=left,grid=major,grid style={black!10},
enlarge y limits=0.08,
]
PLOTS
\draw[<->,black!70] (axis cs:8,LOW) -- (axis cs:8,HIGH);
\node[anchor=north west,align=left,font=\small,fill=white,inner sep=2pt]
at (rel axis cs:0.03,0.97) {$\Delta\log_{10}M=SHIFT$ dex\\Mass factor: $FACTOR$};
\end{axis}
\end{tikzpicture}
\end{minipage}'''.replace('TITLE', title).replace('PLOTS', '\n'.join(plots))
            .replace('LOW', f'{low:.8f}').replace('HIGH', f'{low + shift:.8f}')
            .replace('FACTOR', f'{10 ** shift:.2f}').replace('SHIFT', f'{shift:.3f}'))
    return r'''% Generated by: .venv/bin/python -m scripts.plot_early_start
% Fixed seed mass 100 Msun, f_Edd=1, B=1; matter+Lambda extrapolation.
\begingroup
\definecolor{earlyorange}{HTML}{D55E00}
\centering
{\small $M_{\rm seed}=100\,M_\odot$, $\overline{f}_{\rm Edd}=1$, $B_{\rm merge}=1$\par}
\vspace{5pt}
\begin{tikzpicture}
\draw[atlasblue,line width=1.2pt] (0,0)--(0.7,0);
\node[anchor=west,font=\small] at (0.8,0) {$z_{\rm start}=30$};
\draw[earlyorange,dashed,line width=1.2pt] (3.8,0)--(4.5,0);
\node[anchor=west,font=\small] at (4.6,0) {$z_{\rm start}=3400$};
\end{tikzpicture}\par
\vspace{6pt}
''' + '\n\\hfill\n'.join(panels) + '\n\\endgroup\n'


if __name__ == '__main__':
    target = Path(__file__).resolve().parents[1] / 'paper/figures/early_start_comparison.tex'
    target.write_text(render())
