"""Generate matched seed-mass tracks in separate z_start=30/3400 panels.

Run from the repository root: .venv/bin/python -m scripts.plot_early_start
"""
from pathlib import Path
import numpy as np
from src import models


SEEDS = ((2, 'atlasblue,solid'), (4, 'earlyorange,dashed'), (5, 'earlygreen,densely dotted'))


def render():
    redshift = np.linspace(12, 6, 121)
    epsilon = 0.1
    expected = models.growth_log10_factor(
        1, epsilon, models.cosmic_time_gyr(30) - models.cosmic_time_gyr(3400))
    tracks = {}
    for seed, _ in SEEDS:
        for start in (30, 3400):
            tracks[seed, start] = models.predicted_log_mbh(seed, 1, epsilon, start, redshift)
        np.testing.assert_allclose(tracks[seed, 3400] - tracks[seed, 30], expected, atol=1e-12)
    panels = []
    for index, start in enumerate((30, 3400)):
        plots = []
        for seed, style in SEEDS:
            coordinates = ' '.join(f'({z:.5f},{mass:.8f})'
                                   for z, mass in zip(redshift, tracks[seed, start]))
            plots.append(r'\addplot[' + style + ',line width=1.2pt] coordinates {'
                         + coordinates + '};')
        title = rf'({chr(97 + index)}) $z_{{\rm start}}={start}$'
        panels.append(r'''\begin{minipage}[t]{0.485\textwidth}
\centering
\begin{tikzpicture}
\begin{axis}[
width=\linewidth,height=5.8cm,
xmin=6,xmax=12,x dir=reverse,xtick={6,7,8,9,10,11,12},
ymin=4,ymax=13.5,ytick={4,6,8,10,12},
xlabel={Observed redshift},ylabel={$\log_{10}(M_{\rm BH}/M_\odot)$},
title={TITLE},title style={at={(0,1.04)},anchor=south west},
tick label style={font=\small},label style={font=\small},
axis lines=left,grid=major,grid style={black!10},
]
PLOTS
\end{axis}
\end{tikzpicture}
\end{minipage}'''.replace('TITLE', title).replace('PLOTS', '\n'.join(plots)))
    return r'''% Generated by: .venv/bin/python -m scripts.plot_early_start
% Fixed epsilon=0.1, f_Edd=1, B=1; matter+Lambda extrapolation.
\begingroup
\definecolor{earlyorange}{HTML}{D55E00}
\definecolor{earlygreen}{HTML}{009E73}
\centering
{\small $\epsilon=0.1$, $\overline{f}_{\rm Edd}=1$, $B_{\rm merge}=1$\par}
\vspace{5pt}
\begin{tikzpicture}
\draw[atlasblue,line width=1.2pt] (0,0)--(0.7,0);
\node[anchor=west,font=\small] at (0.8,0) {$M_{\rm seed}=10^2M_\odot$};
\draw[earlyorange,dashed,line width=1.2pt] (4.0,0)--(4.7,0);
\node[anchor=west,font=\small] at (4.8,0) {$10^4M_\odot$};
\draw[earlygreen,densely dotted,line width=1.2pt] (7.0,0)--(7.7,0);
\node[anchor=west,font=\small] at (7.8,0) {$10^5M_\odot$};
\end{tikzpicture}\par
\vspace{6pt}
''' + '\n\\hfill\n'.join(panels) + r'''
\par\vspace{3pt}
{\small Earlier onset raises each matched track by 0.868 dex (a factor of 7.37).\par}
\endgroup
'''


if __name__ == '__main__':
    target = Path(__file__).resolve().parents[1] / 'paper/figures/early_start_comparison.tex'
    target.write_text(render())
